# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Prerak Garg

description:      'I am an astronomy PhD candidate at University of Florida. I work on modeling nebular line emission in galaxy formation simulations. I am currently in my final year'
url:              https://prerakgarg07.github.io
baseurl:          /

github:
  repo:           https://github.com/prerakgarg07/prerakgarg07.github.io

