# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Prerak Garg

description:      ''
url:              https://prerakgarg07.github.io
baseurl:          /

github:
  repo:           https://github.com/prerakgarg07/prerakgarg07.github.io

